{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Mini-Data Set Preparation"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "At the end of running the data prep notebook here, you will have training, development and test data sets"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "dev_data -> the development split of the training data\n",
    "dev_labels -> labels for that\n",
    "\n",
    "train_data -> the training split of the training_data\n",
    "train_lables -> the labels for that\n",
    "\n",
    "test_data -> THE ACTUAL CLICKS TEST TEST data!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Things we've discovered:\n",
    "* Multiple ad_id per display_id\n",
    "* Multiple display_id per document_id\n",
    "* Ad_id can be in multiple display_id and multiple document_id\n",
    "* Only one ad_id per display_id is clicked"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": false,
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import copy\n",
    "import sklearn\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.linear_model import LogisticRegression"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "collapsed": false,
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/sarahkelley/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.\n",
      "  interactivity=interactivity, compiler=compiler, result=result)\n"
     ]
    }
   ],
   "source": [
    "clicks_train_og = pd.read_csv(\"clicks_train.csv\")\n",
    "promoted_content_og = pd.read_csv(\"promoted_content.csv\")\n",
    "doc_cats_og = pd.read_csv(\"documents_categories.csv\")\n",
    "doc_ents_og = pd.read_csv(\"documents_entities.csv\")\n",
    "doc_meta_og = pd.read_csv(\"documents_meta.csv\")\n",
    "doc_topics_og = pd.read_csv(\"documents_topics.csv\")\n",
    "events_og = pd.read_csv(\"events.csv\")\n",
    "page_views_og = pd.read_csv(\"page_views_sample.csv\")\n",
    "clicks_test_og = pd.read_csv(\"clicks_test.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "collapsed": false,
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "doc_ids = set(page_views_og['document_id']) & set(promoted_content_og['document_id'])\n",
    "# pull in the content that is in both page_views and promoted_content\n",
    "events = events_og[events_og['document_id'].isin(doc_ids)]\n",
    "clicks_train = clicks_train_og[clicks_train_og['display_id'].isin(events['display_id'])]\n",
    "events = events[events['display_id'].isin(clicks_train['display_id'])]\n",
    "promoted_content = promoted_content_og[promoted_content_og['ad_id'].isin(clicks_train['ad_id'])]\n",
    "doc_cats = doc_cats_og[doc_cats_og['document_id'].isin(promoted_content['document_id'])]\n",
    "doc_ents = doc_ents_og[doc_ents_og['document_id'].isin(promoted_content['document_id'])]\n",
    "doc_meta = doc_meta_og[doc_meta_og['document_id'].isin(promoted_content['document_id'])]\n",
    "doc_topics = doc_topics_og[doc_topics_og['document_id'].isin(promoted_content['document_id'])]\n",
    "page_views = page_views_og[page_views_og['document_id'].isin(events['document_id'])]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Make master data merging all features to clicks_train"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Merge information about the displays to master dataset\n",
    "Events are only if the user CLICKED. This dataset will bring in information about the display_id's from events"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def click_percent(dataset, ad_id, default_result, reg):\n",
    "    '''Returns the posterior probability of ad being clicked.\n",
    "    If ad has not been encountered before, assume mean click\n",
    "    \n",
    "    dataset is the TRAINING data'''\n",
    "    \n",
    "    # count number of times ad has been seen\n",
    "    ad_total = len(dataset[dataset['ad_id'] == ad_id])\n",
    "    \n",
    "    # if ad has not been seen, returned the default_results\n",
    "    if ad_total == 0:\n",
    "        return default_result\n",
    "    # otherwise return percentage of times ad has been clicked, adjusted by a regularization term\n",
    "    else:\n",
    "        click_sum = np.sum(dataset[dataset['ad_id'] == ad_id].clicked) + 1.0\n",
    "        return click_sum / (ad_total + reg)\n",
    "    \n",
    "def format_data(dataset):\n",
    "\n",
    "    # Merging information aout the displays to master dataset\n",
    "    data = dataset.merge(events, on='display_id', how='left')\n",
    "    # joins information about the display that the user saw\n",
    "    # each display has a unique user id, doc id, and timestamp\n",
    "    # events has the information about the display (who the user is, which site (document_id) it was on, when it was seen, from where, etc.)\n",
    "\n",
    "    # Identifying which documents the ads refer to (aka destination documents)\n",
    "\n",
    "    data = data.merge(promoted_content, on='ad_id', how='left')\n",
    "\n",
    "    # Gather/bin data about the documents the ads refer to\n",
    "\n",
    "    sparsetop = doc_topics.pivot(index='document_id', \n",
    "                                 columns='topic_id', \n",
    "                                 values='confidence_level')\n",
    "    sparsetop.columns = ['top_' + str(col) for col in sparsetop.columns]\n",
    "\n",
    "    sparsecat = doc_cats.pivot(index='document_id', \n",
    "                               columns='category_id', \n",
    "                               values='confidence_level')\n",
    "    sparsecat.columns = ['cat_' + str(col) for col in sparsecat.columns]\n",
    "\n",
    "    sparse = sparsetop.join(sparsecat, how='outer')\n",
    "    sparse.fillna(0, inplace=True)\n",
    "\n",
    "    sparse.reset_index(level=0, inplace=True)\n",
    "\n",
    "    data = data.merge(sparse, \n",
    "                      left_on='document_id_y', \n",
    "                      right_on='document_id', \n",
    "                      how='left')\n",
    "    \n",
    "    # Adding meta data about the advertiser and campaign successes\n",
    "    if 'clicked' in clicks_train.columns:\n",
    "        advr_success = dict(zip(data.advertiser_id.unique(), \n",
    "                                [sum(data[data['advertiser_id']==x]['clicked'])/len(data[data['advertiser_id']==x]) for x in data['advertiser_id'].unique()]))\n",
    "        camp_success = dict(zip(data.campaign_id.unique(), \n",
    "                                [sum(data[data['campaign_id']==x]['clicked'])/len(data[data['campaign_id']==x]) for x in data['campaign_id'].unique()]))\n",
    "\n",
    "        data['campaign_perc'] = data['campaign_id'].map(camp_success)\n",
    "        data['advertiser_perc'] = data['advertiser_id'].map(advr_success)\n",
    "\n",
    "        doc_view_freq = dict(zip(page_views.document_id.unique(), [len(page_views[page_views.document_id==x]) for x in page_views.document_id.unique()]))\n",
    "        data['docx_view_freq'] = data['document_id_x'].map(doc_view_freq)\n",
    "\n",
    "        # Adding meta data about prior click percentage\n",
    "        mean_click = np.mean(dataset[\"clicked\"])\n",
    "        click_success = dict(zip(data.ad_id.unique(), [click_percent(dataset, x, mean_click, 10.0) for x in dataset[\"ad_id\"].unique()] ))\n",
    "        data['click_perc'] = data['ad_id'].map(click_success)\n",
    "    \n",
    "    return data\n",
    "    \n",
    "    \n",
    "click_train_data = format_data(clicks_train)\n",
    "#data_test = format_data(clicks_test) # doesn't work with click_test yet\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>display_id</th>\n",
       "      <th>ad_id</th>\n",
       "      <th>clicked</th>\n",
       "      <th>uuid</th>\n",
       "      <th>document_id_x</th>\n",
       "      <th>timestamp</th>\n",
       "      <th>platform</th>\n",
       "      <th>geo_location</th>\n",
       "      <th>document_id_y</th>\n",
       "      <th>campaign_id</th>\n",
       "      <th>...</th>\n",
       "      <th>cat_2002</th>\n",
       "      <th>cat_2003</th>\n",
       "      <th>cat_2004</th>\n",
       "      <th>cat_2005</th>\n",
       "      <th>cat_2006</th>\n",
       "      <th>cat_2100</th>\n",
       "      <th>campaign_perc</th>\n",
       "      <th>advertiser_perc</th>\n",
       "      <th>docx_view_freq</th>\n",
       "      <th>click_perc</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>37</td>\n",
       "      <td>70153</td>\n",
       "      <td>0</td>\n",
       "      <td>d4f62cdcb39ad8</td>\n",
       "      <td>1779285</td>\n",
       "      <td>2687</td>\n",
       "      <td>2</td>\n",
       "      <td>US&gt;WA&gt;819</td>\n",
       "      <td>933716</td>\n",
       "      <td>7516</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.045455</td>\n",
       "      <td>0.046069</td>\n",
       "      <td>7701</td>\n",
       "      <td>0.052632</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>37</td>\n",
       "      <td>149047</td>\n",
       "      <td>0</td>\n",
       "      <td>d4f62cdcb39ad8</td>\n",
       "      <td>1779285</td>\n",
       "      <td>2687</td>\n",
       "      <td>2</td>\n",
       "      <td>US&gt;WA&gt;819</td>\n",
       "      <td>1169985</td>\n",
       "      <td>16636</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.137931</td>\n",
       "      <td>0.137931</td>\n",
       "      <td>7701</td>\n",
       "      <td>0.076923</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>37</td>\n",
       "      <td>169564</td>\n",
       "      <td>0</td>\n",
       "      <td>d4f62cdcb39ad8</td>\n",
       "      <td>1779285</td>\n",
       "      <td>2687</td>\n",
       "      <td>2</td>\n",
       "      <td>US&gt;WA&gt;819</td>\n",
       "      <td>1394819</td>\n",
       "      <td>20109</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>7701</td>\n",
       "      <td>0.071429</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>37</td>\n",
       "      <td>234713</td>\n",
       "      <td>1</td>\n",
       "      <td>d4f62cdcb39ad8</td>\n",
       "      <td>1779285</td>\n",
       "      <td>2687</td>\n",
       "      <td>2</td>\n",
       "      <td>US&gt;WA&gt;819</td>\n",
       "      <td>1586431</td>\n",
       "      <td>245</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.265217</td>\n",
       "      <td>0.271255</td>\n",
       "      <td>7701</td>\n",
       "      <td>0.281250</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>37</td>\n",
       "      <td>235443</td>\n",
       "      <td>0</td>\n",
       "      <td>d4f62cdcb39ad8</td>\n",
       "      <td>1779285</td>\n",
       "      <td>2687</td>\n",
       "      <td>2</td>\n",
       "      <td>US&gt;WA&gt;819</td>\n",
       "      <td>1377696</td>\n",
       "      <td>11654</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.043478</td>\n",
       "      <td>0.082631</td>\n",
       "      <td>7701</td>\n",
       "      <td>0.043478</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 411 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   display_id   ad_id  clicked            uuid  document_id_x  timestamp  \\\n",
       "0          37   70153        0  d4f62cdcb39ad8        1779285       2687   \n",
       "1          37  149047        0  d4f62cdcb39ad8        1779285       2687   \n",
       "2          37  169564        0  d4f62cdcb39ad8        1779285       2687   \n",
       "3          37  234713        1  d4f62cdcb39ad8        1779285       2687   \n",
       "4          37  235443        0  d4f62cdcb39ad8        1779285       2687   \n",
       "\n",
       "  platform geo_location  document_id_y  campaign_id     ...      cat_2002  \\\n",
       "0        2    US>WA>819         933716         7516     ...             0   \n",
       "1        2    US>WA>819        1169985        16636     ...             0   \n",
       "2        2    US>WA>819        1394819        20109     ...             0   \n",
       "3        2    US>WA>819        1586431          245     ...             0   \n",
       "4        2    US>WA>819        1377696        11654     ...             0   \n",
       "\n",
       "   cat_2003  cat_2004  cat_2005  cat_2006  cat_2100  campaign_perc  \\\n",
       "0         0         0         0         0         0       0.045455   \n",
       "1         0         0         0         0         0       0.137931   \n",
       "2         0         0         0         0         0       0.000000   \n",
       "3         0         0         0         0         0       0.265217   \n",
       "4         0         0         0         0         0       0.043478   \n",
       "\n",
       "   advertiser_perc  docx_view_freq  click_perc  \n",
       "0         0.046069            7701    0.052632  \n",
       "1         0.137931            7701    0.076923  \n",
       "2         0.000000            7701    0.071429  \n",
       "3         0.271255            7701    0.281250  \n",
       "4         0.082631            7701    0.043478  \n",
       "\n",
       "[5 rows x 411 columns]"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "click_train_data.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now we are merging information on what documents the ads referred to (from source: promoted_content).  \n",
    "In every display, there are multiple ads (within one document = document_id_x). Every ad refers to a different document, which is the site the ad is promoting (document_id_y). All the columns after document_id_y are information about that document (to which the ad is referring)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Merge information about the documents the ads refer to\n",
    "All the doc files have information about the documents (websites) to which the ads refer to\n",
    "including confidence levels of which topics the ads referred to, which categories they're apart of, etc.\n",
    "\n",
    "We wanted to duplicate the idea of the CountVectorizer for the 'bag of words' model we used for spam detection, but since we're not counting words in a text, it's a little bit different. Since we have a 'dictionary' of categories and topics, we use that as our 'vocabulary.' Every document has a confidence level for one or more items in the vocabulary, so we create a sparse matrix with every topic and category as columns, and every document has a confidence level value in the respective columns. If they are not given a confidence level, we put 0 because the document most likely does not have anything to do with that category or topic (given the data provided by Outbrain).\n",
    "\n",
    "This data on the documents will help us separate ads from one another based on topic/category.  \n",
    "ie) why did ad A get clicked instead of ad B? We know ad A referred to document 1 whereas ad B referred to document 2, and now we have general information about the documents the ads referred to. We will merge this information in later steps."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "creating dictionaries for % of ads clicked for every advertiser and campaign.  \n",
    "purpose: merge to master dataset as a feature for every ad, how often the advertiser and campaign are successful on average."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Add count of page views to every document that an ad appears in (document_id_x) as a feature, could tell us something about likelihood of ads being clicked"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Click_train Predictions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "doc_ids = set(page_views_og['document_id']) & set(promoted_content_og['document_id'])\n",
    "# pull in the content that is in both page_views and promoted_content\n",
    "events_test = events_og[events_og['document_id'].isin(doc_ids)]\n",
    "clicks_test = clicks_test_og[clicks_test_og['display_id'].isin(events_test['display_id'])]\n",
    "events_test = events_test[events_test['display_id'].isin(clicks_test['display_id'])]\n",
    "promoted_content_test = promoted_content_og[promoted_content_og['ad_id'].isin(clicks_test['ad_id'])]\n",
    "doc_cats_test = doc_cats_og[doc_cats_og['document_id'].isin(promoted_content_test['document_id'])]\n",
    "doc_ents_test = doc_ents_og[doc_ents_og['document_id'].isin(promoted_content_test['document_id'])]\n",
    "doc_meta_test = doc_meta_og[doc_meta_og['document_id'].isin(promoted_content_test['document_id'])]\n",
    "doc_topics_test = doc_topics_og[doc_topics_og['document_id'].isin(promoted_content_test['document_id'])]\n",
    "page_views_test = page_views_og[page_views_og['document_id'].isin(events_test['document_id'])]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def click_percent(dataset, ad_id, default_result, reg):\n",
    "    '''Returns the posterior probability of ad being clicked.\n",
    "    If ad has not been encountered before, assume mean click\n",
    "    \n",
    "    dataset is the TRAINING data'''\n",
    "    \n",
    "    # count number of times ad has been seen\n",
    "    ad_total = len(dataset[dataset['ad_id'] == ad_id])\n",
    "    \n",
    "    # if ad has not been seen, returned the default_results\n",
    "    if ad_total == 0:\n",
    "        return default_result\n",
    "    # otherwise return percentage of times ad has been clicked, adjusted by a regularization term\n",
    "    else:\n",
    "        click_sum = np.sum(dataset[dataset['ad_id'] == ad_id].clicked) + 1.0\n",
    "        return click_sum / (ad_total + reg)\n",
    "    \n",
    "def format_test_data(dataset, train):\n",
    "\n",
    "    # Merging information aout the displays to master dataset\n",
    "    data = dataset.merge(events_test, on='display_id', how='left')\n",
    "    # joins information about the display that the user saw\n",
    "    # each display has a unique user id, doc id, and timestamp\n",
    "    # events has the information about the display (who the user is, which site (document_id) it was on, when it was seen, from where, etc.)\n",
    "\n",
    "    # Identifying which documents the ads refer to (aka destination documents)\n",
    "\n",
    "    data = data.merge(promoted_content_test, on='ad_id', how='left')\n",
    "\n",
    "    # Gather/bin data about the documents the ads refer to\n",
    "\n",
    "    sparsetop = doc_topics.pivot(index='document_id', \n",
    "                                 columns='topic_id', \n",
    "                                 values='confidence_level')\n",
    "    sparsetop.columns = ['top_' + str(col) for col in sparsetop.columns]\n",
    "\n",
    "    sparsecat = doc_cats.pivot(index='document_id', \n",
    "                               columns='category_id', \n",
    "                               values='confidence_level')\n",
    "    sparsecat.columns = ['cat_' + str(col) for col in sparsecat.columns]\n",
    "\n",
    "    sparse = sparsetop.join(sparsecat, how='outer')\n",
    "    sparse.fillna(0, inplace=True)\n",
    "\n",
    "    sparse.reset_index(level=0, inplace=True)\n",
    "\n",
    "    data = data.merge(sparse, \n",
    "                      left_on='document_id_y', \n",
    "                      right_on='document_id', \n",
    "                      how='left')\n",
    "    \n",
    "    # Adding meta data about the advertiser and campaign successes\n",
    "    advr_success = dict(zip(data.advertiser_id.unique(), \n",
    "                            [(sum(train[train['advertiser_id']==x]['clicked'])/len(train[train['advertiser_id']==x])) if (len(train[train['advertiser_id']==x]) != 0) else np.mean(train['clicked']) for x in data['advertiser_id'].unique()]))\n",
    "    camp_success = dict(zip(data.campaign_id.unique(), \n",
    "                            [sum(train[train['campaign_id']==x]['clicked'])/len(train[train['campaign_id']==x]) if (len(train[train['campaign_id']==x]) != 0) else np.mean(train['clicked']) for x in data['campaign_id'].unique()]))\n",
    "\n",
    "    data['campaign_perc'] = data['campaign_id'].map(camp_success)\n",
    "    data['advertiser_perc'] = data['advertiser_id'].map(advr_success)\n",
    "\n",
    "    doc_view_freq = dict(zip(page_views_test.document_id.unique(), [len(page_views_test[page_views_test.document_id==x]) for x in page_views_test.document_id.unique()]))\n",
    "    data['docx_view_freq'] = data['document_id_x'].map(doc_view_freq)\n",
    "\n",
    "    # Adding meta data about prior click percentage\n",
    "    mean_click = np.mean(train[\"clicked\"])\n",
    "    click_success = dict(zip(data.ad_id.unique(), [click_percent(train, x, mean_click, 10.0) for x in dataset[\"ad_id\"].unique()] ))\n",
    "    data['click_perc'] = data['ad_id'].map(click_success)\n",
    "    \n",
    "    return data\n",
    "    \n",
    "    \n",
    "test_data = format_test_data(clicks_test, click_train_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>display_id</th>\n",
       "      <th>ad_id</th>\n",
       "      <th>uuid</th>\n",
       "      <th>document_id_x</th>\n",
       "      <th>timestamp</th>\n",
       "      <th>platform</th>\n",
       "      <th>geo_location</th>\n",
       "      <th>document_id_y</th>\n",
       "      <th>campaign_id</th>\n",
       "      <th>advertiser_id</th>\n",
       "      <th>...</th>\n",
       "      <th>cat_2002</th>\n",
       "      <th>cat_2003</th>\n",
       "      <th>cat_2004</th>\n",
       "      <th>cat_2005</th>\n",
       "      <th>cat_2006</th>\n",
       "      <th>cat_2100</th>\n",
       "      <th>campaign_perc</th>\n",
       "      <th>advertiser_perc</th>\n",
       "      <th>docx_view_freq</th>\n",
       "      <th>click_perc</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>16875069</td>\n",
       "      <td>57252</td>\n",
       "      <td>bc19371a0fb69b</td>\n",
       "      <td>1649400</td>\n",
       "      <td>182688</td>\n",
       "      <td>3</td>\n",
       "      <td>US&gt;CA&gt;803</td>\n",
       "      <td>758162</td>\n",
       "      <td>7659</td>\n",
       "      <td>285</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.114253</td>\n",
       "      <td>9943</td>\n",
       "      <td>0.052632</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>16875069</td>\n",
       "      <td>61159</td>\n",
       "      <td>bc19371a0fb69b</td>\n",
       "      <td>1649400</td>\n",
       "      <td>182688</td>\n",
       "      <td>3</td>\n",
       "      <td>US&gt;CA&gt;803</td>\n",
       "      <td>992370</td>\n",
       "      <td>7283</td>\n",
       "      <td>1919</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.011401</td>\n",
       "      <td>0.013349</td>\n",
       "      <td>9943</td>\n",
       "      <td>0.014599</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>16875069</td>\n",
       "      <td>132857</td>\n",
       "      <td>bc19371a0fb69b</td>\n",
       "      <td>1649400</td>\n",
       "      <td>182688</td>\n",
       "      <td>3</td>\n",
       "      <td>US&gt;CA&gt;803</td>\n",
       "      <td>1160307</td>\n",
       "      <td>17030</td>\n",
       "      <td>285</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.144444</td>\n",
       "      <td>0.114253</td>\n",
       "      <td>9943</td>\n",
       "      <td>0.140449</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>16875069</td>\n",
       "      <td>153427</td>\n",
       "      <td>bc19371a0fb69b</td>\n",
       "      <td>1649400</td>\n",
       "      <td>182688</td>\n",
       "      <td>3</td>\n",
       "      <td>US&gt;CA&gt;803</td>\n",
       "      <td>987161</td>\n",
       "      <td>19525</td>\n",
       "      <td>1913</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.071542</td>\n",
       "      <td>0.044244</td>\n",
       "      <td>9943</td>\n",
       "      <td>0.075163</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>16875069</td>\n",
       "      <td>228959</td>\n",
       "      <td>bc19371a0fb69b</td>\n",
       "      <td>1649400</td>\n",
       "      <td>182688</td>\n",
       "      <td>3</td>\n",
       "      <td>US&gt;CA&gt;803</td>\n",
       "      <td>1141938</td>\n",
       "      <td>25174</td>\n",
       "      <td>2712</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.230007</td>\n",
       "      <td>0.221762</td>\n",
       "      <td>9943</td>\n",
       "      <td>0.229416</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 410 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   display_id   ad_id            uuid  document_id_x  timestamp platform  \\\n",
       "0    16875069   57252  bc19371a0fb69b        1649400     182688        3   \n",
       "1    16875069   61159  bc19371a0fb69b        1649400     182688        3   \n",
       "2    16875069  132857  bc19371a0fb69b        1649400     182688        3   \n",
       "3    16875069  153427  bc19371a0fb69b        1649400     182688        3   \n",
       "4    16875069  228959  bc19371a0fb69b        1649400     182688        3   \n",
       "\n",
       "  geo_location  document_id_y  campaign_id  advertiser_id     ...      \\\n",
       "0    US>CA>803         758162         7659            285     ...       \n",
       "1    US>CA>803         992370         7283           1919     ...       \n",
       "2    US>CA>803        1160307        17030            285     ...       \n",
       "3    US>CA>803         987161        19525           1913     ...       \n",
       "4    US>CA>803        1141938        25174           2712     ...       \n",
       "\n",
       "   cat_2002  cat_2003  cat_2004  cat_2005  cat_2006  cat_2100  campaign_perc  \\\n",
       "0         0         0         0         0         0         0       0.000000   \n",
       "1         0         0         0         0         0         0       0.011401   \n",
       "2         0         0         0         0         0         0       0.144444   \n",
       "3         0         0         0         0         0         0       0.071542   \n",
       "4         0         0         0         0         0         0       0.230007   \n",
       "\n",
       "   advertiser_perc  docx_view_freq  click_perc  \n",
       "0         0.114253            9943    0.052632  \n",
       "1         0.013349            9943    0.014599  \n",
       "2         0.114253            9943    0.140449  \n",
       "3         0.044244            9943    0.075163  \n",
       "4         0.221762            9943    0.229416  \n",
       "\n",
       "[5 rows x 410 columns]"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "test_data.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": true
   },
   "source": [
    "# Make training and test sets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Labels length: 282205\n",
      "data length: (282205, 410)\n",
      "training label shape:  (197543, 1)\n",
      "training data shape:  (197543, 410)\n",
      "dev label shape: (84662, 1)\n",
      "dev data shape: (84662, 410)\n"
     ]
    }
   ],
   "source": [
    "def dev_train_split(data, train_percent = False):\n",
    "    # Splitting dataset into data and labels\n",
    "\n",
    "    labels = data['clicked']\n",
    "    labels = labels.values.reshape(-1,1)\n",
    "    del data['clicked']\n",
    "\n",
    "    print('Labels length:', len(labels))\n",
    "    print('data length:', data.shape)\n",
    "\n",
    "    # Making training and test set splits\n",
    "    # if not split defined, assume no split desired.\n",
    "    # split_percent = 1 means test results will be empty\n",
    "    if not train_percent:\n",
    "        train_percent = 1\n",
    "        \n",
    "    train_data = data[:int(train_percent*len(data))]\n",
    "    dev_data = data[int(train_percent*len(data)):]\n",
    "\n",
    "    train_labels = labels[:int(train_percent*len(data))]\n",
    "    dev_labels = labels[int(train_percent*len(data)):]\n",
    "\n",
    "    print('training label shape: ', train_labels.shape)\n",
    "    print('training data shape: ' , train_data.shape)\n",
    "    print('dev label shape:', dev_labels.shape)\n",
    "    print ('dev data shape:', dev_data.shape)\n",
    "    \n",
    "    return train_data, train_labels, dev_data, dev_labels\n",
    "\n",
    "train_data, train_labels, dev_data, dev_labels = dev_train_split(click_train_data, train_percent = 0.7)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## What the files are now called:\n",
    "dev_data -> the development split of the training data\n",
    "dev_labels -> labels for that\n",
    "\n",
    "train_data -> the training split of the training_data\n",
    "train_lables -> the labels for that\n",
    "\n",
    "test_data -> THE ACTUAL CLICKS TEST TEST data!\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>display_id</th>\n",
       "      <th>ad_id</th>\n",
       "      <th>uuid</th>\n",
       "      <th>document_id_x</th>\n",
       "      <th>timestamp</th>\n",
       "      <th>platform</th>\n",
       "      <th>geo_location</th>\n",
       "      <th>document_id_y</th>\n",
       "      <th>campaign_id</th>\n",
       "      <th>advertiser_id</th>\n",
       "      <th>...</th>\n",
       "      <th>cat_2002</th>\n",
       "      <th>cat_2003</th>\n",
       "      <th>cat_2004</th>\n",
       "      <th>cat_2005</th>\n",
       "      <th>cat_2006</th>\n",
       "      <th>cat_2100</th>\n",
       "      <th>campaign_perc</th>\n",
       "      <th>advertiser_perc</th>\n",
       "      <th>docx_view_freq</th>\n",
       "      <th>click_perc</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>197543</th>\n",
       "      <td>12392612</td>\n",
       "      <td>332065</td>\n",
       "      <td>f7bc18373c9d55</td>\n",
       "      <td>1854517</td>\n",
       "      <td>824018058</td>\n",
       "      <td>2</td>\n",
       "      <td>GB&gt;J9</td>\n",
       "      <td>1710793</td>\n",
       "      <td>29309</td>\n",
       "      <td>210</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.044444</td>\n",
       "      <td>0.066400</td>\n",
       "      <td>222</td>\n",
       "      <td>0.037736</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>197544</th>\n",
       "      <td>12392612</td>\n",
       "      <td>377111</td>\n",
       "      <td>f7bc18373c9d55</td>\n",
       "      <td>1854517</td>\n",
       "      <td>824018058</td>\n",
       "      <td>2</td>\n",
       "      <td>GB&gt;J9</td>\n",
       "      <td>1913629</td>\n",
       "      <td>104</td>\n",
       "      <td>162</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.061311</td>\n",
       "      <td>0.061324</td>\n",
       "      <td>222</td>\n",
       "      <td>0.050000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>197545</th>\n",
       "      <td>12392612</td>\n",
       "      <td>466261</td>\n",
       "      <td>f7bc18373c9d55</td>\n",
       "      <td>1854517</td>\n",
       "      <td>824018058</td>\n",
       "      <td>2</td>\n",
       "      <td>GB&gt;J9</td>\n",
       "      <td>2288852</td>\n",
       "      <td>246</td>\n",
       "      <td>232</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.400000</td>\n",
       "      <td>0.271255</td>\n",
       "      <td>222</td>\n",
       "      <td>0.090909</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>197546</th>\n",
       "      <td>12392612</td>\n",
       "      <td>489002</td>\n",
       "      <td>f7bc18373c9d55</td>\n",
       "      <td>1854517</td>\n",
       "      <td>824018058</td>\n",
       "      <td>2</td>\n",
       "      <td>GB&gt;J9</td>\n",
       "      <td>2392456</td>\n",
       "      <td>104</td>\n",
       "      <td>162</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.061311</td>\n",
       "      <td>0.061324</td>\n",
       "      <td>222</td>\n",
       "      <td>0.090909</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>197547</th>\n",
       "      <td>12392620</td>\n",
       "      <td>86365</td>\n",
       "      <td>52990e5aa41541</td>\n",
       "      <td>1649400</td>\n",
       "      <td>824018294</td>\n",
       "      <td>3</td>\n",
       "      <td>GB&gt;H3</td>\n",
       "      <td>1105913</td>\n",
       "      <td>11172</td>\n",
       "      <td>2222</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.202265</td>\n",
       "      <td>0.252889</td>\n",
       "      <td>9943</td>\n",
       "      <td>0.201867</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 410 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        display_id   ad_id            uuid  document_id_x  timestamp platform  \\\n",
       "197543    12392612  332065  f7bc18373c9d55        1854517  824018058        2   \n",
       "197544    12392612  377111  f7bc18373c9d55        1854517  824018058        2   \n",
       "197545    12392612  466261  f7bc18373c9d55        1854517  824018058        2   \n",
       "197546    12392612  489002  f7bc18373c9d55        1854517  824018058        2   \n",
       "197547    12392620   86365  52990e5aa41541        1649400  824018294        3   \n",
       "\n",
       "       geo_location  document_id_y  campaign_id  advertiser_id     ...      \\\n",
       "197543        GB>J9        1710793        29309            210     ...       \n",
       "197544        GB>J9        1913629          104            162     ...       \n",
       "197545        GB>J9        2288852          246            232     ...       \n",
       "197546        GB>J9        2392456          104            162     ...       \n",
       "197547        GB>H3        1105913        11172           2222     ...       \n",
       "\n",
       "        cat_2002  cat_2003  cat_2004  cat_2005  cat_2006  cat_2100  \\\n",
       "197543         0         0         0         0         0         0   \n",
       "197544         0         0         0         0         0         0   \n",
       "197545         0         0         0         0         0         0   \n",
       "197546         0         0         0         0         0         0   \n",
       "197547         0         0         0         0         0         0   \n",
       "\n",
       "        campaign_perc  advertiser_perc  docx_view_freq  click_perc  \n",
       "197543       0.044444         0.066400             222    0.037736  \n",
       "197544       0.061311         0.061324             222    0.050000  \n",
       "197545       0.400000         0.271255             222    0.090909  \n",
       "197546       0.061311         0.061324             222    0.090909  \n",
       "197547       0.202265         0.252889            9943    0.201867  \n",
       "\n",
       "[5 rows x 410 columns]"
      ]
     },
     "execution_count": 39,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "test_data.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Following Homework2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# SK-learn libraries for learning.\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.naive_bayes import BernoulliNB\n",
    "from sklearn.naive_bayes import MultinomialNB\n",
    "from sklearn.grid_search import GridSearchCV\n",
    "\n",
    "# SK-learn libraries for evaluation.\n",
    "from sklearn.metrics import confusion_matrix\n",
    "from sklearn import metrics\n",
    "from sklearn.metrics import classification_report\n",
    "\n",
    "# SK-learn library for importing the newsgroup data.\n",
    "from sklearn.datasets import fetch_20newsgroups\n",
    "\n",
    "# SK-learn libraries for feature extraction from text.\n",
    "from sklearn.feature_extraction.text import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {
    "collapsed": false,
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "def lr_prediction(dev_data, dev_labels, train_data, train_labels):\n",
    "    '''Returns the array of display_id, ad_id and probability it will be clicked'''\n",
    "    lr = LogisticRegression()\n",
    "    lr.fit(train_data[train_data.columns[11:]].fillna(0), train_labels)\n",
    "    lr_click_prob = lr.predict_proba(dev_data[dev_data.columns[11:]].fillna(0))[:,1]\n",
    "    lr_score = lr.score(dev_data[dev_data.columns[11:]].fillna(0), dev_labels)\n",
    "    return pd.DataFrame({'display_id': dev_data['display_id'],\n",
    "                         'ad_id': dev_data['ad_id'],\n",
    "                         'prediction': lr_click_prob\n",
    "                        })"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def lr_test_prediction(test_data, train_data, train_labels):\n",
    "    '''As above but works on the unlabeled test data\n",
    "    Returns the array of display_id, ad_id and probability it will be clicked'''\n",
    "    lr = LogisticRegression()\n",
    "    lr.fit(train_data[train_data.columns[11:]].fillna(0), train_labels)\n",
    "    lr_click_prob = lr.predict_proba(dev_data[dev_data.columns[11:]].fillna(0))[:,1]\n",
    "    return pd.DataFrame({'display_id': dev_data['display_id'],\n",
    "                         'ad_id': dev_data['ad_id'],\n",
    "                         'prediction': lr_click_prob\n",
    "                        })"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/sarahkelley/anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().\n",
      "  y = column_or_1d(y, warn=True)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ad_id</th>\n",
       "      <th>display_id</th>\n",
       "      <th>prediction</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>197543</th>\n",
       "      <td>332065</td>\n",
       "      <td>12392612</td>\n",
       "      <td>0.074205</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>197544</th>\n",
       "      <td>377111</td>\n",
       "      <td>12392612</td>\n",
       "      <td>0.071809</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>197545</th>\n",
       "      <td>466261</td>\n",
       "      <td>12392612</td>\n",
       "      <td>0.245085</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>197546</th>\n",
       "      <td>489002</td>\n",
       "      <td>12392612</td>\n",
       "      <td>0.087257</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>197547</th>\n",
       "      <td>86365</td>\n",
       "      <td>12392620</td>\n",
       "      <td>0.197833</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         ad_id  display_id  prediction\n",
       "197543  332065    12392612    0.074205\n",
       "197544  377111    12392612    0.071809\n",
       "197545  466261    12392612    0.245085\n",
       "197546  489002    12392612    0.087257\n",
       "197547   86365    12392620    0.197833"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "lr_output = lr_test_prediction(test_data, train_data, train_labels)\n",
    "lr_output.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "# Format the data the way the submission requires\n",
    "lr_output.sort_values(['display_id','prediction'],inplace=True,ascending=False)\n",
    "output=lr_output.groupby(['display_id'])['ad_id'].apply(lambda x:' '.join(map(str,x))).reset_index()\n",
    "output.head()\n",
    "# That's it for the simple solution (prior expectation)!\n",
    "output.to_csv('simple_test_solution.cvs',index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
